language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
cache:
  npm: false

matrix:
  include:
    - name: Lint
      node_js: 12
      script: npm run lint

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphicsmagick
      - inkscape

script: npm run test:ci
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/da6c90cc3857ade1086c
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
